<style type="text/css">

    .halign{
        
        margin-left: 20px;      
        max-width: 810px;
    }

    .btn-group{
        padding: 5px;
        margin-left: 10px;
    }

    .horario{
        padding: 10px;
        background:rgba(255,0,0,.5); 
    }

    .horario table{
        background: ccc;
    }

    #hola{
        background: #ccc;
    }

    #box1{
        margin: 15px;
    }

</style>
<!-- Latest compiled and minified CSS 
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

<!-- Optional theme 
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript 
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>-->
<div class="horario" >
    <img id="box1" src="<? echo $this->rutaImagenes ?>horario.png" alt="">
    
    <div id="box2" class="halign">
        <form id="miform" method="POST" action="/rovi/index/index">

        <div class="input-append">
    

                <select id="servicio" name="servicio" >
                        <?
                        $arregloServicio = $this->parametros['Servicios'];
                        foreach ($arregloServicio as $key => $value) {
                            echo '<option value="' . $value["idProveedor_Servicio"] . '">' . $value['Nombre'] . '</option>';
                        }
                        ?>
                </select>

            <button class="btn btn-info" type="submit"><strong>Cargar</strong></button>
        </div>          
        </form>
    </div>
    <br>
    <div class="btn-group" id="daypicker">        
            <?
            echo $this->parametros['menudias'];
            ?>        
        <button type="button" class="btn btn-default" >></button>
    </div>
    <div id="hola">
        <table class="table table-striped table-bordered">
            <?
            echo $this->parametros['grid'];
            ?>
        </table> 
    </div>
     

</div>
<div>

</div>

<?
//var_dump($this->parametros['horario']);
?>