<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
        <title>Programate</title>
        <link rel="stylesheet" href="/templates/default/css/estilos.css">
        <script>
        </script>
    </head>
    <body>
        
       
        <section id="contenedor">
            <!--Cabecera-->
            <header>
                <img src="<? echo $this->rutaImagenes ?>logo.png" width="130px">
                
                <div id='menu2'>
                    <img alt="" src="/templates/default/img/boton_menu.png"
                         width="50px">
                    <ul>
                        <li>hola</li>
                    </ul>
                </div>
            </header>



            <!--contenido-->
            <section id="webs">

                <?php
                require $this->menuHTML;
                ?>

                <?php
                require $this->contenidoURL;
                ?>

            </section>

            <footer>
                <br>copyright&COPY Iteraxis.co 2013
                <br>Todos los derechos reservados

            </footer>
        </section>

    </body>
</html>
