
<nav>
    <ul>
        <li><a href="/index/home/index">Ahora</a></li>
        <li><a href="/index/home/programar">Programar</a></li>
        <li><a href="/index/home/cine">En cine</a></li>
        <li id="campo"><div class="ima"></div></li>
        <li><a href="/index/home/ayuda">Ayuda</a></li>
        <li><a href="/index/home/donacion">Donación</a></li>
        <li>
                
            <a href="https://www.facebook.com/dialog/oauth?client_id=458867537554408&response_type=code%20token&scope=user_events,user_likes&redirect_uri=http://anfho93.sytes.net/facebook/home/confirmarIdentidad">Login face</a></li>                
    </ul>

</nav>
