<nav>
    <ul>
        <li><a href=".?modulo=index&controlador=home&metodo=index">Ahora</a></li>
        <li><a href=".?modulo=index&controlador=home&metodo=programar">Programar</a></li>
        <li><a href=".?modulo=index&controlador=home&metodo=cine">En cine</a></li>
        <li id="campo"><div class="ima"></div></li>
        <li><a href=".?modulo=index&controlador=home&metodo=Sugerir">Sugerir</a></li>
        <li><a href=".?modulo=index&controlador=home&metodo=ayuda">Ayuda</a></li>
        <li><a href=".?modulo=index&controlador=home&metodo=donacion">Donación</a></li>
    </ul>
</nav>