<div id='menu2'>
    <a href="#"><img alt="" src="/templates/default/img/boton_menu.png"
                     width="40px"></a>
    <ul>
        <li>
            <?
            if (empty($_COOKIE['programate'])) {
                ?>
                <a href="https://www.facebook.com/dialog/oauth?client_id=458867537554408&response_type=code&scope=user_likes&redirect_uri=http://anfho93.sytes.net/facebook/home/confirmarIdentidad">Login face</a></li>                
            <?
        } else {
            ?>
            <a href="/facebook/home/logOut">Cerrar Sesion</a></li>        
        <? } ?>
        <li><a href="/index/home/index">Ahora</a></li>
        <li><a href="/index/home/programar">Programar</a></li>
        <li><a href="/index/home/cine">En cine</a></li>
        <li><a href="/index/sugerir/mispreferencias">sugerir</a></li>
        <li><a href="/index/home/ayuda">Ayuda</a></li>
        <li><a href="/index/home/donacion">donacion</a></li>
    </ul>
</div>