<style type="text/css">
    #programa{
        color: black;
        border: 1px solid white;
        background: #ccc;
        box-sizing: border-box;
        -webkit-transition: .2s;
        -moz-transition: .2s;
        transition: .2s;
        margin-top:30px;
        padding: 5px;
    }
</style>             
        

<?php
$cant = $this->parametros['cant'];
$HTML = "";
for ($i = 1; $i <= $cant; $i++) {
    $programa = $this->parametros['programa' . $i];
    $HTML.= '<div class="row-fluid">
                <div class="span10 offset1" id="programa">

                    <div class="row-fluid">
                        <div class="span2" id="programa">
                            <img src=" '.$this->rutaImagenes.'desafio.jpg" alt="Desafio Africa"/>
                            hola
                        </div>
                        <div class="span2" id="canal">
                            <img src="'.$this->rutaImagenes.'caracol-tv.jpg" alt="Caracol TV"/>
                        </div>
                        <div class="span8" id="info">
                            <h1>';
                                $HTML.= $programa['titulo'] . '
                            </h1>
                            <p> '
                                . $programa['info'] . '
                             </p>
                        </div>
                    </div>
                </div>
            </div>';
}
echo $HTML;
?>

<div class="espFooter">
</div>