<?
//$peliculas = 
var_dump($this->parametros['peliculas']);
/*foreach ($peliculas as $key => $value) {
    if($value['category']=='Movie')
    foreach ($value as $k => $v) {
        echo $k." : ".$v."<br/>";
    }
    
}*/

echo '\n';
$programa = $this->parametros['programas'];
foreach ($programa as $key => $value) {
    if($value['category']=='Tv show')
      foreach ($value as $k => $v) {
        echo $k." : ".$v."<br/>";
    }
    
}

?>